name: Lint

on:
  push:
    branches: ["**"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/lint.yml"

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff-black:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Sync dev deps
        run: uv sync --locked --group dev --no-install-project

      - name: Ruff (errors only)
        run: uv run --group dev ruff check --select E9,F63,F7,F82 --output-format=github .

      - name: Ruff format (check)
        run: uv run --group dev ruff format --check .

      - name: Black (check)
        run: uv run --group dev black --check .
