name: Lint

on:
  push:
    branches: ["**"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "unirec/requirements.txt"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "unirec/requirements.txt"
      - ".github/workflows/lint.yml"

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff-black:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: unirec/requirements.txt

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r unirec/requirements.txt
          pip install ruff black

      # Static checks (only critical rules for early stage; expand later)
      - name: Ruff (errors only)
        run: |
          ruff check --select E9,F63,F7,F82 --output-format=github .

      # Formatting checks
      - name: Ruff format (check)
        run: ruff format --check .

      - name: Black (check)
        run: black --check .
