name: Test

on:
  push:
    branches: ["**"]
    paths:
      - "**.py"
      - "unirec/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "**.py"
      - "unirec/**"
      - "tests/**"
      - ".github/workflows/test.yml"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: unirec/requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r unirec/requirements.txt
          pip install pytest pytest-cov

      # Ensure repo always has at least one test
      - name: Ensure smoke test
        run: |
          if ! ls tests/*.py >/dev/null 2>&1; then
            mkdir -p tests
            cat > tests/test_smoke.py <<'PY'
            def test_smoke():
                assert True
            PY
          fi

      - name: Run pytest
        env:
          PYTHONPATH: .
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=unirec --cov-report=xml --cov-report=term-missing

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
