name: Type Check

on:
  push:
    branches: ["**"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "unirec/requirements.txt"
      - ".github/workflows/typecheck.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "unirec/requirements.txt"
      - ".github/workflows/typecheck.yml"

concurrency:
  group: type-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: unirec/requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r unirec/requirements.txt
          pip install mypy

      - name: Run mypy
        run: |
          mypy unirec \
            --ignore-missing-imports \
            --install-types --non-interactive
